
# Understanding Vector Search Techniques: iVFlat, HNSW, and DiskANN

This notebook provides an overview and comparison of three popular methods used in vector search: **iVFlat**, **HNSW (Hierarchical Navigable Small World)**, and **DiskANN**. We will explore their characteristics, strengths, and appropriate use cases.
    


## 1. What is Vector Search?

Vector search refers to finding similar vectors in a high-dimensional space. It is commonly used in applications such as:

- **Recommendation Systems**: Suggesting items based on similarity.
- **Semantic Search**: Retrieving results based on meaning rather than exact text match.
- **Image/Video Retrieval**: Finding similar multimedia content.
    


## 2. Overview of Techniques

### 2.1 iVFlat (Inverted Flat Index)
- **Description**: Combines an inverted index with flat vector storage.
- **Advantages**:
  - Simple and efficient for smaller datasets.
  - Exact search is possible.
- **Limitations**:
  - Requires significant memory for large datasets.
  - Slower query times compared to approximate methods.

### 2.2 HNSW (Hierarchical Navigable Small World)
- **Description**: Graph-based approach to approximate nearest neighbor (ANN) search.
- **Advantages**:
  - Fast query times.
  - Good balance of accuracy and speed.
- **Limitations**:
  - High memory usage.
  - Build times can be significant for large datasets.

### 2.3 DiskANN (Disk-friendly ANN)
- **Description**: Optimized for datasets larger than RAM capacity; uses disk-based storage efficiently.
- **Advantages**:
  - Handles extremely large datasets by leveraging SSDs.
  - Low memory footprint.
- **Limitations**:
  - Slower than in-memory methods.
  - SSD performance can be a bottleneck.
    


## 3. Comparison of Techniques

| Feature                  | iVFlat            | HNSW                     | DiskANN              |
|--------------------------|-------------------|--------------------------|----------------------|
| **Data Structure**       | Inverted index    | Graph-based              | Disk + RAM           |
| **Memory Usage**         | High              | Medium-High              | Low (RAM) + Disk     |
| **Query Time Complexity**| Linear            | Logarithmic              | Logarithmic          |
| **Build Time Complexity**| Low               | High                     | Medium               |
| **Scalability**          | Poor (RAM bound)  | Medium                   | Excellent (disk support)|
| **Best Use Cases**       | Small datasets    | Fast in-memory search    | Large-scale datasets |

### Key Considerations
- Use **iVFlat** for simple and small datasets.
- Choose **HNSW** for high-speed, in-memory searches with high accuracy.
- Opt for **DiskANN** when working with datasets exceeding RAM capacity.
    

In [5]:
%pip install faiss-cpu

Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/13.8 MB ? eta -:--:--
   ---- ----------------------------------- 1.6/13.8 MB 9.3 MB/s eta 0:00:02
   --------- ------------------------------ 3.4/13.8 MB 8.7 MB/s eta 0:00:02
   -------------- ------------------------- 5.0/13.8 MB 8.9 MB/s eta 0:00:01
   ------------------- -------------------- 6.8/13.8 MB 8.6 MB/s eta 0:00:01
   ------------------------ --------------- 8.7/13.8 MB 8.7 MB/s eta 0:00:01
   ------------------------------- -------- 11.0/13.8 MB 9.0 MB/s eta 0:00:01
   ------------------------------------- -- 13.1/13.8 MB 9.1 MB/s eta 0:00:01
   ---------------------------------------- 13.8/13.8 MB 9.0 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [ ]:

# Example: Using HNSW for Vector Search with Faiss

import numpy as np
import faiss

# Generate random data
d = 128  # Dimension
nb = 10000  # Database size
nq = 5  # Number of queries

np.random.seed(1234)
database = np.random.random((nb, d)).astype('float32')
queries = np.random.random((nq, d)).astype('float32')

# Build index
index = faiss.IndexHNSWFlat(d, 32)  # 32 is the number of neighbors
index.add(database)

# Perform search
k = 4  # Number of nearest neighbors
distances, indices = index.search(queries, k)
print("Indices of nearest neighbors:", indices)
print("Distances to nearest neighbors:", distances)
    

Indices of nearest neighbors: [[4044 2826 7775 4722]
 [2762 6644 5217 4221]
 [5596 1617  106 3321]
 [7167 4062 1648 9815]
 [5531 9262 2933 7668]]
Distances to nearest neighbors: [[14.519493  14.9778385 15.132271  15.136276 ]
 [15.277808  16.032898  16.185116  16.32803  ]
 [15.646384  15.67143   15.70339   16.04276  ]
 [13.788441  14.625786  14.823555  14.890352 ]
 [13.655877  13.713434  13.981209  15.026011 ]]



## 4. Conclusion

Each method has its strengths and weaknesses. The choice of method depends on the size of your dataset, available memory, and query time requirements:

- **iVFlat**: Best for small, simple datasets.
- **HNSW**: Excellent for fast in-memory approximate search.
- **DiskANN**: Ideal for massive datasets that exceed RAM capacity.

Feel free to explore the provided code to understand how HNSW works in practice!
    